### ISSUE TITLE
Release Notes text on Issue

### ISSUE THREAD

**Issue by HLCharlie** [Medology/.github#26]
# Description
Currently, the text that should be Slacked in either devteam, releasenotes, or both upon completion of a Bug, Feature, or Technical Issue is prompted for in the template of a PR. With our new process of one PR per Issue it would make sense to move release text to the Issue. This will allow the SM to see and review the text and help with the wording at least for those that go to the releasenotes channel. Also, it appears that not everyone is using the PR template for all PRs so sometimes the text is never even available for review by anyone until it is released.

## Negative Impact:
Announcement text varies greatly in content and clarity. Some (many?) times the text is reviewed by no one other than the author. Text to the end users is inconsistent between Issues resolved. Often the messages are too succinct or incomplete. This situation can confuse the end users and may cause unnecessary questions and feedback.

## Proposed Solution:
Move the text from the PR template to the Issue template. Have it reviewed along with the other sections of the Issue by the team and by the SM. Add an "Announcement Text" section in the Issue template to contain the text. Add checkboxes to Pre-Production QA for the creation of the text and one to PO Approval for the SM review of the text.

## How will the proposed solution address the negative impact(s)?
Having the user story right there when creating the text will help the developer craft a clearer message. Also having the announcement text on the Issue will enable the SM to review the text and offer suggestions.

## Side Effects
none anticipated

## QA Needs
no QA testing required

# Acceptance Criteria
- [x] Announcement Message section header and explanation added to all Issue templates
- [x] checkbox added to criteria for Pre-Production QA in all templates
- [x] checkbox added to criteria for SM Approval in all templates

# Announcement Message
releasenotes: N/A
devteam: "All Issue templates have been updated to include an Announcement Message section to capture the messages that you will put in devteam and/or releasenotes channels. A Progress checkbox for the creation of the announcement message has also been added to the SM Approval list. Please follow the instructions in the template for all new Issues created. Modifying existing Issues is optional."

# Progress
### Ready for Planning
- [x] Story and Business Value complete
- [x] Initial Acceptance Criteria Defined
- [x] The person who will Approve story identified
- [x] Proposed Solution provided

### Ready for Review
- [x] Testing implemented and passed

### Ready for Pre-Production QA
- [x] Issue scored
- [x] Special testing instructions noted
- [x] Acceptance criteria met - boxes checked
- [x] Announcement message created

### Ready for SM Approval
- [x] Manual Acceptance Test Results included in Comment

### Ready for PO Approval
- [x] Issue complete and correct in all required sections
- [x] All checkboxes checked
- [x] Announcement message approved

**Comment by Chekote** [comment]
Verified that sections are present for all three templates:

![Screen Shot 2020-09-25 at 1.25.02 PM.png](https://images.zenhubusercontent.com/57d18ae5e40e5714b16e8533/a269981a-0e79-4b71-b783-085142babc09)

![Screen Shot 2020-09-25 at 1.25.07 PM.png](https://images.zenhubusercontent.com/57d18ae5e40e5714b16e8533/242dfecc-3dbe-40d7-8121-3aaeec39521e)

![Screen Shot 2020-09-25 at 1.25.14 PM.png](https://images.zenhubusercontent.com/57d18ae5e40e5714b16e8533/29f11022-e470-4450-84c7-398d96c771b6)
